/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#5f5e5e',
        'on-primary-fixed': '#1c1b1b',
        'secondary-fixed-dim': '#abd600',
        'inverse-surface': '#e5e2e1',
        'on-secondary-fixed': '#161e00',
        'surface-container-lowest': '#0e0e0e',
        error: '#ffb4ab',
        secondary: '#ffffff',
        'secondary-fixed': '#c3f400',
        'secondary-container': '#c3f400',
        'on-secondary': '#283500',
        'primary-fixed-dim': '#c9c6c5',
        'error-container': '#93000a',
        background: '#131313',
        'on-surface-variant': '#c4c7c7',
        'on-primary': '#313030',
        'on-surface': '#e5e2e1',
        'on-primary-container': '#7b7979',
        'outline-variant': '#444748',
        'surface-container-high': '#2a2a2a',
        'primary-container': '#0a0a0a',
        tertiary: '#d0bcff',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'on-secondary-container': '#556d00',
        'inverse-on-surface': '#313030',
        'tertiary-fixed-dim': '#d0bcff',
        'on-secondary-fixed-variant': '#3c4d00',
        surface: '#131313',
        primary: '#c9c6c5',
        'primary-fixed': '#e5e2e1',
        'surface-bright': '#393939',
        'on-tertiary': '#3c0091',
        'on-tertiary-fixed-variant': '#5516be',
        outline: '#8e9192',
        'surface-container-highest': '#353535',
        'on-primary-fixed-variant': '#474646',
        'surface-tint': '#c9c6c5',
        'surface-container-low': '#1c1b1b',
        'on-tertiary-container': '#895af4',
        'surface-dim': '#131313',
        'surface-variant': '#353535',
        'on-background': '#e5e2e1',
        'surface-container': '#20201f',
        'tertiary-container': '#0e002f',
        'tertiary-fixed': '#e9ddff',
        'on-tertiary-fixed': '#23005c',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '64px',
        gutter: '24px',
        'margin-mobile': '16px',
        'stack-sm': '8px',
        'stack-lg': '32px',
        'stack-md': '16px',
        'stack-xl': '64px',
        'container-max': '1440px',
        unit: '4px',
      },
      fontFamily: {
        'headline-xl': ['Syne', 'sans-serif'],
        'data-display': ['"JetBrains Mono"', 'monospace'],
        'headline-lg': ['Syne', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Syne', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-mono': ['"JetBrains Mono"', 'monospace'],
        'headline-md': ['Syne', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['80px', { lineHeight: '1.0', letterSpacing: '-0.04em', fontWeight: '800' }],
        'data-display': ['14px', { lineHeight: '1.0', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.1', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-mono': ['12px', { lineHeight: '1.4', letterSpacing: '0.1em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
      },
      maxWidth: {
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
};
